databases:
  - name: Oodas_DB
    databaseName: oodas_db
    user: Oodas
    region: singapore

services:
  - type: web
    name: Oodas
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Oodas_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
